### ISSUE TITLE
Offline support with service workers

### ISSUE THREAD

**Issue by rwaldron** [jennschiffer/make8bitart#51]
Let's explore what this actually means. What things should make8bitart do if there is no network?
- it should probably Just Work™ as though the operator were connected to a network 
  - network first, cache as fallback

This is just a starting point place to iron out the details and come up with a strategy before a bunch of code gets written.

Note that the site will have to move to https

**Comment by jennschiffer** [comment]
I moved the site to https this afternoon!

**Comment by jennschiffer** [comment]
i finished this tonight! https://github.com/jennschiffer/make8bitart/commit/e4502f9d9a9e4da6368265438c25a412335152ac
