### ISSUE TITLE
Network Establishment

### ISSUE THREAD

**Issue by AliensComeback** [jennschiffer/make8bitart#53]
When I try to go to make8bitart, It slows when establishing network connection, then it says this site can't be reached, the error code is ERR_TIMED_OUT, i am not using a proxy server at all.

**Comment by jennschiffer** [comment]
are you still having an issue? everything seems to be working on my end. i'm thinking maybe the server was down temporarily for maintenance or whatever. feel free to open this issue if you have more trouble.

**Comment by AliensComeback** [comment]
Thanks you! It works :3
