### ISSUE TITLE
snap not published in the Ubuntu store

### ISSUE THREAD

**Issue by elopio** [jennschiffer/make8bitart#58]
Hello again!

Last thing I mentioned in #56 was that it would be great to have the snap in the store, so I can be easily installed by any ubuntu user.

Now we have a new system to build and publish snaps, which is in beta now. So it would be awesome if you can give it a try. It should take a couple of minutes to set everything up for automated delivery:
https://build.snapcraft.io/

Any comments about the service would be great ^_^

pura vida

**Comment by jennschiffer** [comment]
i'm putting this on hold until i have time to explore what this entails - i don't want to have to support make8bitart out of the context of just here on the web but i'll report back if things change. thanks for introducing it to me!
