### ISSUE TITLE
Export to pxon not working

### ISSUE THREAD

**Issue by jeremybbauer** [jennschiffer/make8bitart#59]
Hello! Love the site. It's so fun, and just what I was looking for with a project I had in mind. 

It seems, though, that the export to pxon function doesn't work. I tried this in Chrome and Opera, and in both cases, clicking [export pxon] opens a blank browser window and nothing else happens. I made a short gif recording in case it's helpful: [https://cl.ly/0h1E2S3u1c3H](https://cl.ly/0h1E2S3u1c3H) . 

Exporting to png with full page and selection still works perfectly 🙂 . 

Thanks for making this beautiful thing!

**Comment by jennschiffer** [comment]
Hi! Sorry for the late response, I don't get much time to work on this lately. Just wanted you to know that I read this and will revisit it in a week or so when I'm done with my conference load!

**Comment by jeremybbauer** [comment]
Oh, no worries! This is great! Wish I was able to help, but I don't have the skills. I'm happy to test or something if needed, though.
